import defaultImg from './assets/defaultImg.svg';
import autorImg from './assets/Circular.svg';

export const articles = [
  {
    lead: 'Lead',
    title:
      'Title esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader:
      'Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Nicolas Hernandez',
    imgautor: autorImg,
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader:
      'Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Aydee Duarte',
    imgautor: autorImg,
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader:
      'Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Robinsson Hernandez',
    imgautor: autorImg,
    url: '#',
  },
  {
    lead: 'Lead',
    title:
      'Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Americo Carrasquero',
    imgautor: autorImg,
    url: '#',
  },
  {
    lead: 'Lead',
    title:
      'Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader:
      'Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Laura Ramirez',
    imgautor: autorImg,
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Ana Victoria',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: 'Marquee',
    autor: 'Luis Diaz',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title:
      'Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: defaultImg,
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title:
      'Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: '',
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: '',
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
  {
    lead: 'Lead',
    title: 'Esto es un titulo de la novedad con unas cuantas lineas que ocupar',
    subheader: '',
    img: '',
    marquee: '',
    autor: '',
    imgautor: '',
    url: '#',
  },
];
