import defaultImg from './assets/defaultImg.svg'

export const articles = [
  {
    lead: "Lead",
    title:
      "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader:
      "Lana soñaba con volar a la luna. Todas las tardes se tumbaba en su cama y se imaginaba comó sería su viaje a bordo de su propia nave espacial",
    img: defaultImg,
    marquee: "Marquee",
    autor: "Nicolas Hernandez",
    imgautor: "https://cdn-icons-png.flaticon.com/512/709/709722.png",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Aydee Duarte",
    imgautor: "https://cdn-icons-png.flaticon.com/512/709/709722.png",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Robinsson Hernandez",
    imgautor: "https://cdn-icons-png.flaticon.com/512/709/709722.png",
    url:"#",
  },
  {
    lead: "Lead",
    title:
      "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Americo Carrasquero",
    imgautor: "https://cdn-icons-png.flaticon.com/512/709/709722.png",
    url:"#",
  },
  {
    lead: "Lead",
    title:
      "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Laura Ramirez",
    imgautor: "https://cdn-icons-png.flaticon.com/512/709/709722.png",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Ana Victoria",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "Marquee",
    autor: "Luis Diaz",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title:
      "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "https://us.123rf.com/450wm/meepoohyaphoto/meepoohyaphoto1309/meepoohyaphoto130900355/22268211-la-imagen-de-fondo-azul-del-dise%C3%B1o-.jpg?ver=6",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title:
      "Title Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
  {
    lead: "Lead",
    title: "Esto es un titulo de la novedad con unas cuantas lineas que ocupar",
    subheader: "",
    img: "",
    marquee: "",
    autor: "",
    imgautor: "",
    url:"#",
  },
];
