export const links = {
  secciones: [
    { link: "Últimas noticias", url: "#" },
    { link: "Política", url: "#" },
    { link: "Economía", url: "#" },
    { link: "El mundo", url: "#" },
    { link: "Sociedad", url: "#" },
    { link: "Opinión", url: "#" },
    { link: "Deportes", url: "#" },
    { link: "Lifestyle", url: "#" },
    { link: "Espectáculos", url: "#" },
    { link: "Edición impresa", url: "#" },
    { link: "LN+", url: "#" },
    { link: "Club LA NACION", url: "#" },
  ],
  revistas: [
    { link: "OHLALÁ!", url: "#" },
    { link: "¡HOLA!", url: "#" },
    { link: "ROLLING STONE", url: "#" },
    { link: "LIVING", url: "#" },
    { link: "BRANDO", url: "#" },
    { link: "JARDÍN", url: "#" },
    { link: "LUGARES", url: "#" },
  ],
  clubvino: [{ link: "Bon vivir", url: "#" }],
  envios: [
    { link: "¡HOLA!", url: "#" },
    { link: "HOP", url: "#" },
    { link: "Colecciones", url: "#" },
    { link: "Máster en periodismo", url: "#" },
    { link: "Fundación LA NACION", url: "#" },
    { link: "Avisos solidarios", url: "#" },
  ],
};
